- docs/UserGuide.md
UserGuide.md:
* add sort feature
* add sort command to command summary
> Add sort feature in UserGuide.md

- docs/DeveloperGuide.md
* add UC03 - Delete a contact
* add UC04 - Sort contacts
* add UC12 - Access peer GitHub information
> Update use cases in DeveloperGuide.md

- docs/DeveloperGuide.md
> Update user stories in DeveloperGuide.md

- docs/team/chia-yh.md
chia-yh.md:
* update AddressBook -> SOCket
* update overview
* update RepoSense link
* update contributions
* add `to be added soon` as placeholders for content
> Add skeletal Project Portfolio Page (PPP)

- docs/DeveloperGuide.md
> Update the glossary in DeveloperGuide.md

- docs/DeveloperGuide.md
* add non-functional requirement - should work on 64-bit environment
> Update the non-functional requirements in DeveloperGuide.md

- docs/UserGuide.md
UserGuide.md:
* update find feature
> Update find features in UserGuide.md

- docs/DeveloperGuide.md
Update DeveloperGuide.md with the following use cases:
* UC05 Find contact(s)
* UC11 Using shortcut command
* UC14 Tagging a contact
> Update Developer Guide with UC05, UC11 and UC14

- src/main/java/seedu/address/logic/commands/SortCommand.java
- src/main/java/seedu/address/logic/parser/AddressBookParser.java
- src/main/java/seedu/address/logic/parser/SortCommandParser.java
- src/main/java/seedu/address/model/AddressBook.java
- src/main/java/seedu/address/model/Model.java
- src/main/java/seedu/address/model/ModelManager.java
- src/main/java/seedu/address/model/person/UniquePersonList.java
- src/test/java/seedu/address/logic/commands/AddCommandTest.java
- src/test/java/seedu/address/logic/commands/SortCommandTest.java
- src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
- src/test/java/seedu/address/logic/parser/SortCommandParserTest.java
- src/test/java/seedu/address/model/person/UniquePersonListTest.java
- src/test/java/seedu/address/testutil/TypicalPersons.java
Add sort command to allow the sorting of the list of contacts.
Currently the user is not able to sort the list of contacts.
The user may want to organize the list by sorting.
Let's
* add sort command that allows the sorting of the list by name, phone, email or address.
SortCommand.java:
* create new Sort Command object that executes sort
SortCommandParser.java
* create new parser to parse arguments for sorting
AddressBookParser.java:
* add new case to the switch to return a new SortCommandParser
Model.java:
* add new sortPersonList function
ModelManager.java
* add new sortPersonList function that sorts addressbook
AddressBook.java:
* add new sort function that sorts persons
UniquePersonList.java:
* add new sort function that sorts the internal list
AddCommandTest.java:
* update test to …
> Add sort feature

- docs/UserGuide.md
Update UserGuide.md for find command to include cases that can search for all fields
> Update UserGuide.md for find command

- docs/UserGuide.md
Add remove command in the UG
Update `Notes about the command format`
> Update UG on remove command

- src/main/java/seedu/address/logic/commands/SortCommand.java
- src/main/java/seedu/address/logic/parser/SortCommandParser.java
- src/main/java/seedu/address/model/person/Person.java
- src/main/java/seedu/address/model/person/UniquePersonList.java
- src/test/java/seedu/address/logic/commands/SortCommandTest.java
- src/test/java/seedu/address/model/person/UniquePersonListTest.java
- src/test/java/seedu/address/testutil/TypicalPersons.java
Update sort feature with ability to sort by GitHub Profile and improve code quality.
* Replace "magic strings" with static constants.
* Add github profile as a sorting category.
* Change success message to indicate category that is sorted by.
Person.java:
* declare constants for category names and list for existing categories
SortCommandParser.java:
* replace magic string with constant
SortCommand.java:
* add category to success message
UniquePersonList.java:
* replace magic strings with constants
* add github profile as a sort option
UniquePersonList.java:
* replace magic strings with constants
* add test to test sorting by github profile
> Update sort feature

- docs/UserGuide.md
UserGuide.md 
- Update list description in UserGuide.md to account for language and tag.
> Update list in UserGuide.md

- src/main/java/seedu/address/MainApp.java
- src/main/java/seedu/address/ui/HelpWindow.java
- src/main/resources/view/HelpWindow.fxml
MainApp.java:
* add static field services to allow access to HostServices
* add method openUrl() to allow for opening of URLs
HelpWindow.java:
* removed USERGUIDE_URL from HELP_MESSAGE
* updated USERGUIDE_URL
* add @FXML Hyperlink field
* add @FXML openUserGuide() method to be called by Hyperlink
HelpWindow.fxml:
* modify format to have Hyperlink, copy URL button aligned under COMMAND_LIST
> Update HelpWindow with clickable Hyperlink

- docs/DeveloperGuide.md
- docs/UserGuide.md
Update UG and DG on the latest implementations
DG: 
- Adds UC17 & UC18
UG:
- Adds view command
> Update UG/DG on remove and view feature

- src/main/java/seedu/address/logic/commands/DeleteCommand.java
What's change:
- Make the detail display empty when the viewed person is deleted
DeleteCommand:
- When the person to delete is the same person as the view person, empty the viewed person
> Fix bug on UX

- src/main/java/seedu/socket/model/Socket.java
- src/main/java/seedu/socket/model/project/Project.java
- src/main/java/seedu/socket/model/project/ProjectMeeting.java
- src/main/java/seedu/socket/model/project/UniqueProjectList.java
- src/main/java/seedu/socket/model/util/SampleDataUtil.java
- src/main/java/seedu/socket/storage/JsonAdaptedProject.java
- src/main/java/seedu/socket/storage/JsonSerializableSocket.java
- src/test/data/JsonSerializableSocketTest/duplicateProjectSocket.json
- src/test/data/JsonSerializableSocketTest/invalidProjectSocket.json
- src/test/data/JsonSerializableSocketTest/missingProjectMemberInPersonsSocket.json
- src/test/data/JsonSerializableSocketTest/typicalProjectsSocket.json
- src/test/java/seedu/socket/logic/commands/CommandTestUtil.java
- src/test/java/seedu/socket/model/project/ProjectMeetingTest.java
- src/test/java/seedu/socket/model/project/ProjectTest.java
- src/test/java/seedu/socket/storage/JsonAdaptedProjectTest.java
- src/test/java/seedu/socket/testutil/ProjectBuilder.java
- src/test/java/seedu/socket/testutil/TypicalProjects.java
Project class currently does not have meeting.  ProjectMeeting class is added so now projects can contain a meeting allowing  users to store more fields in a project. 
**Project.java**
- Update Project.java to handle meeting field 
**ProjectMeeting.java**
- Similar to ProjectDeadline.java 
**UniqueProjectList.java**
- Update sort() to sort meetings 
**SampleDataUtil.java**
- Update getSamplePersons() 
**JsonUpdatedProject.java**
- Update to handle meeting
**JsonSerializableSocket.java**
- Update to handle meeting 
**CommandTestUtil.java**
- Add valid project meeting strings
**ProjectMeetingTest.java**
- To test for ProjectMeeting class
**JsonAdaptedProjectTest.java**
- Add tests to handle meeting 
**ProjectBuilder.java**
- Update to handle meeting 
**TypicalProjects.java**
- Add meetings …
> Add meeting to project

- src/main/java/seedu/socket/logic/commands/ClearProjectCommand.java
Add commitSocket into clearpj command to allow undo/redo feature
> Add command clearpj

- docs/UserGuide.md
- src/main/java/seedu/socket/logic/commands/UnassignCommand.java
- src/main/java/seedu/socket/logic/parser/SocketParser.java
- src/main/java/seedu/socket/logic/parser/UnassignCommandParser.java
- src/main/java/seedu/socket/model/project/Project.java
- src/test/java/seedu/socket/logic/commands/UnassignCommandTest.java
- src/test/java/seedu/socket/logic/parser/SocketParserTest.java
- src/test/java/seedu/socket/logic/parser/UnassignCommandParserTest.java
- src/test/java/seedu/socket/model/project/ProjectTest.java
UnassignCommand.java:
* Create UnassignCommand object
UnassignCommandParser.java:
* Create parser that returns an UnassignCommand object
SocketParser.java:
* Add case for UnassignCommand
Implement relevant tests
> Add unassign command

- docs/DeveloperGuide.md
* Add use case for sorting projects
* Add use case for unassigning a member
* Fix typo in UC04
> Update use cases for sortpj and unassign commands

- src/main/java/seedu/socket/model/project/ProjectName.java
- src/test/java/seedu/socket/model/person/NameTest.java
- src/test/java/seedu/socket/model/project/ProjectNameTest.java
- src/test/java/seedu/socket/model/project/ProjectTest.java
Update duplicate checking to be case insensitive, consecutive spaces are now invalid
> Refine duplicate checking for Project instances

- src/test/java/seedu/socket/model/person/predicate/FindCommandAddressPredicateTest.java
- src/test/java/seedu/socket/model/person/predicate/FindCommandEmailPredicateTest.java
- src/test/java/seedu/socket/model/person/predicate/FindCommandLanguagePredicateTest.java
- src/test/java/seedu/socket/model/person/predicate/FindCommandNamePredicateTest.java
- src/test/java/seedu/socket/model/person/predicate/FindCommandPersonPredicateTest.java
- src/test/java/seedu/socket/model/person/predicate/FindCommandPhonePredicateTest.java
- src/test/java/seedu/socket/model/person/predicate/FindCommandProfilePredicateTest.java
- src/test/java/seedu/socket/model/person/predicate/FindCommandTagPredicateTest.java
- src/test/java/seedu/socket/model/person/tag/LanguageTest.java
- src/test/java/seedu/socket/model/person/tag/TagTest.java
* Shift tag test package to be inside person test package for src/test to match location of tag package in src/main
* Rename predicate test files to match new predicate names in src/main
> Refactor test case names and location

- docs/UserGuide.md
* add missing `...`
* reshuffle sections so that General Features comes last, `help` comes right before Saving/Editing data
* Fix some formatting issues
* Extracted point into tip for edit
* Fixes #224
> Update UG, fix documentation bugs

- src/main/java/seedu/socket/model/project/ProjectDeadline.java
- src/main/java/seedu/socket/model/project/ProjectMeeting.java
- src/test/java/seedu/socket/model/project/ProjectDeadlineTest.java
- src/test/java/seedu/socket/model/project/ProjectMeetingTest.java
Date allows invalid dates such as 31 February
Enables the DateTimeFormatter to reject such invalid dates
Update ProjectDeadlineTest and ProjectMeetingTest to test invalid dates
> Fix date formatter

- docs/UserGuide.md
Add list of valid categories for sorting
Add tip for user informing them that sort will sort and display the entire contact list
> Update UG for sort and sortpj

- src/main/java/seedu/socket/logic/commands/EditProjectCommand.java
Fix error message for editpj to a valid format.
> fix error message for editpj

- docs/UserGuide.md
- src/main/java/seedu/socket/ui/HelpWindow.java
Fix error in help window for the following commands: addpj and assign.
Edit user guide so that editpj in ug match in help window.
> fix help command error

- src/main/java/seedu/socket/logic/commands/RemoveCommand.java
- src/main/java/seedu/socket/logic/commands/RemoveProjectCommand.java
Previous messages in remove and removepj were incorrect and misleading. Changed to 'Removed field from Person:'.
> edit message in remove

- docs/DeveloperGuide.md
- docs/team/cmang12.md
> add use cases

- docs/UserGuide.md
- Fix error in command format for edit, remove & removepj.
- Add remarks regarding empty prefixes.
> Update UG to fix errors and add remarks.
